### ISSUE TITLE
Melhoria no código de ConsoleRealPlayer

### ISSUE THREAD

**Issue by papb** [papb/jdv#17]
Aquela variável `count` começa em zero e é sempre incrementada, e testada se é zero ou não, então pensando bem seria melhor ser um boolean né, algo como `firstRun` que começa em `true` e depois vira `false`, é mais intuitivo para esse caso do que um contador, então podia mudar isso.

**Comment by davilrolim** [comment]
#19 Foi criada uma variável boolean beginning que substitui o contador
