### ISSUE TITLE
Não é possível descobrir qual o jogador ao implementar a AI

### ISSUE THREAD

**Issue by marcelohoffman** [papb/jdv#8]
Na interface IPlayerAI não contém a informação sobre se o jogador é X ou O, impossibilitando a implementação de uma AI invencível.

**Comment by papb** [comment]
De fato, vou dar uma olhada nisso. Inclusive, acho que não só na AI, mas desde o IPlayer já deveria ter um jeito bom de ver se você é X ou O...

Deixa comigo
